apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
spec:
 replicas: 3
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest@
        ports:
        - containerPort: "80"
        resources:
          request:
            memory: 256Mi
            cpu: 100m
      terminationGracePeriodSeconds: "30"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer-type
  ports:
  - port: 80
    protocol: HTTP
    targetPort: 80