apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application-linting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-linting
  template:
    metadata:
      labels:
        app: web-app-linting
    spec:
      automountServiceAccountToken: false
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.19.0        
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
        volumeMounts:
        - mountPath: /var/log
          name: log-volume
          readOnly: true
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
            ephemeral-storage: 1Gi
          requests:
            memory: 256Mi
            cpu: 200m
            ephemeral-storage: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 30
      volumes:
      - name: log-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-service-security
spec:
  type: LoadBalancer
  selector:
    app: web-app-linting
  ports:
  - port: 80
    targetPort: 80